FROM maven:3-openjdk-14 AS build

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

ADD . /usr/src/app

RUN mvn install -DskipTests

FROM maven:3-openjdk-14

COPY --from=build /usr/src/app/target/oko-0.0.1-SNAPSHOT.jar ./oko.jar

CMD ["java", "-jar", "oko.jar"]